### ISSUE TITLE
Rebase systemd to v250 in RHEL-9

### ISSUE THREAD

**Issue by msekletar** [redhat-plumbers/systemd-rhel9#58]
This is the tracker where I will summarise work items that need to happen in order to successfully deliver new systemd version v250 in RHEL-9.

## TODO
- [x] Create rebase bug in Red Hat Bugzilla 
https://bugzilla.redhat.com/show_bug.cgi?id=2047768
- [x] Prepare new content of the `main` branch (systemd-stable/v250-stable + RHEL-only patches) 
https://github.com/msekletar/rhel-9/commits/main
- [x] Rebase `main` to `v250.3` + downstream patches (i.e. content from previous item)
https://github.com/redhat-plumbers/systemd-rhel9/commits/main
- [x] Upload new sources to CentOS Stream 9 look aside cache
- [x] Prepare CentOS stream merge request with the rebase
https://gitlab.com/redhat/centos-stream/rpms/systemd/-/merge_requests/42
scratch build: https://kojihub.stream.rdu2.redhat.com/koji/taskinfo?taskID=914983
- [x] Review and merge CentOS Stream 9 PR
**merged**
- [x] Review all currently proposed PRs and figure out whether they are still relevant, if so then rebase them on top of `main`
- [x] Verify CI configuration
- [x] Change spec file to use the same version numbering scheme as in RHEL-8 (SAP request)
https://gitlab.com/redhat/centos-stream/rpms/systemd/-/merge_requests/43
- [x] Add `rhel-9.0.0` network naming scheme
https://github.com/redhat-plumbers/systemd-rhel9/pull/68

**Comment by jamacku** [comment]
> * [x]  Prepare new content of the `main` branch (systemd-stable/v250-stable + RHEL-only patches)
> https://github.com/msekletar/rhel-9/commits/main

I noticed missing tags from `systemd-stable` repo.

**Comment by msekletar** [comment]
@jamacku Good point. However, I see that tags are now pushed to this repo so we should be all set.

**Comment by msekletar** [comment]
@dtardon @jacekmigacz can you please check contents of your opened PRs and rebase them or close them in case they aren't relevant anymore?

**Comment by jamacku** [comment]
> @jamacku Good point. However, I see that tags are now pushed to this repo so we should be all set.

We still missing a lot of tags from `systemd-stable`, I just added tag `250.3` to mark last commit of rebase.

**Comment by mrc0mmand** [comment]
The CI seems to work apart from unprivileged containers. However, that should get fixed by #56.

**Comment by dtardon** [comment]
> @dtardon @jacekmigacz can you please check contents of your opened PRs and rebase them or close them in case they aren't relevant anymore?

Done.

**Comment by jacekmigacz** [comment]
I'm proposing another solution for naming scheme definition in https://github.com/redhat-plumbers/systemd-rhel9/pull/63.

**Comment by jamacku** [comment]
We can close this issue, only thing missing is #70
